#!/bin/sh

# You can call this script like this:
# $ ./deviceControl.sh audio up|down|mute
# $ ./deviceControl.sh mic mute
# $ ./deviceControl.sh brightness up|down
#
# Dependencies: dunstify brightnessctl pactl
#
# Acknowledgements:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

get_volume() {
  pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{print substr($5, 1, length($5)-1)}'
}

is_mute() {
  pactl get-sink-mute @DEFAULT_SINK@ | grep yes > /dev/null
}

is_mic_mute() {
  pactl get-source-mute @DEFAULT_SOURCE@ | grep yes > /dev/null
}

get_brightness() {
  max_bright=$(cat /sys/class/backlight/intel_backlight/max_brightness)
  act_bright=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
  echo $(( (act_bright*100+(max_bright/2))/max_bright ))
}

get_level_icon() {
  if [ "$1" -le 0 ] ; then
    printf %s "$2-none-dark"
  elif [ "$1" -le 30 ] ; then
    printf %s "$2-low-dark"
  elif [ "$1" -le 85 ] ; then
    printf %s "$2-medium-dark"
  elif [ "$1" -le 100 ] ; then
    printf %s "$2-high-dark"
  else
    printf %s "$2-overamplified-dark"
  fi
}

draw_bar() {
  percentual=$1
  slices=$2
  lvl=$((percentual / slices))
  empty_lvl=$(((100 / slices) - lvl))
  n=0
  lvl_bar=""
  while [ $n -lt $lvl ]; do
    lvl_bar="$lvl_bar"█
    n=$((n + 1))
  done
  n=0
  while [ $n -lt $empty_lvl ]; do
    lvl_bar="$lvl_bar"░
    n=$((n + 1))
  done
  printf "%s" "$lvl_bar"
}

send_notification() {
  if [ "$1" = "audio" ] ; then
    replace_id=2593
    if is_mute ; then
      notif_icon="audio-volume-muted-dark"
      notif_text="Audio Muted"
    else
      level=$(get_volume)
      notif_icon=$(get_level_icon "$level" "audio-volume")
      notif_text="$(draw_bar "$level" 5)"
    fi
  elif [ "$1" = "mic" ]; then
    replace_id=2594
    if is_mic_mute ; then
      notif_icon="microphone-sensitivity-muted"
      notif_text="Microphone Muted"
    else
      notif_icon="microphone-sensitivity-high"
      notif_text="Microphone On"
    fi
  elif [ "$1" = "brightness" ] ; then
    replace_id=2595
    if [ ! -d "/sys/class/backlight/intel_backlight/" ]; then
      notif_icon="display-brightness-disabled-dark"
      notif_text="Backlight Disabled"
    else
      level="$(get_brightness)"
      notif_icon=$(get_level_icon "$level" "display-brightness")
      notif_text="$(draw_bar "$level" 5)"
    fi
  else
    replace_id=2590
    notif_icon="dialog-error"
    notif_text="Script-error: option not found"
  fi
  # Send the notification
  dunstify -i $notif_icon -r $replace_id -u normal "$notif_text"
}

# Change default sink volume and toggle on/mute
# In case of volume change, unmute first
set_audio() {
  case $1 in
    up)
      pactl set-sink-mute @DEFAULT_SINK@ 0
      pactl set-sink-volume @DEFAULT_SINK@ +5%
      send_notification audio
      ;;
    down)
      pactl set-sink-mute @DEFAULT_SINK@ 0
      pactl set-sink-volume @DEFAULT_SINK@ -5%
      send_notification audio
      ;;
    mute)
      pactl set-sink-mute @DEFAULT_SINK@ toggle
      send_notification audio
      ;;
    *)
      printf "Unrecognized audio setting!"
      exit 1
      ;;
  esac
}

# increase/decrease the backlight by 5%
set_brightness() {
  case $1 in
    up)
      brightnessctl s +5%
      send_notification brightness
      ;;
    down)
      brightnessctl s 5%-
      send_notification brightness
      ;;
    *)
      printf "Unrecognized brightness setting!"
      exit 1
      ;;
  esac
}

set_mic() {
  case $1 in
    mute)
      pactl set-source-mute @DEFAULT_SOURCE@ toggle
      send_notification mic
      ;;
    *)
      printf "Unrecognized mic setting!"
      exit 1
      ;;
  esac
}

case $1 in
  audio)
    set_audio "$2"
    ;;
  brightness)
    set_brightness "$2"
    ;;
  mic)
    set_mic "$2"
    ;;
  *)
    printf "Unrecognized argument!"
    exit 1
    ;;
esac
